### ISSUE TITLE
Tutorials: Chords

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding.github.io#132]
In the Chords tutorial, the XPath rules enforce a specific order of the containing notes, which is more strict than MEI itself and confusing. This should be relaxed to allow any order of notes within each chord.

https://github.com/music-encoding/music-encoding.github.io/blob/cba73555599bd9e00e8d6456ae3d61963a423282/_tutorials/103_chords/103_chords.json#L67

**Comment by musicEnfanthen** [comment]
See the point. Would it work to have something like:

`{"rule":"//mei:note/@pname = 'e' and //mei:note/@oct = '4'", "renderanyway": true, "hint": "You need a note with a @pname attribute with a value of e and an @oct attribute with a value of 4."},`

However, the first hint of this kind would then be displayed until you enter this specific note of the chord (even if you start with all the other notes) because the xpaths rules get checked one after the other.

**Comment by musicEnfanthen** [comment]
The above would check for note with pname e and any (other) note with octave 4.

`{"rule":"//mei:note[@pname = 'e' and @oct = '4']"}`

should do the trick to match one note element with both attributes. Correct?
