### ISSUE TITLE
Background: literature references

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding.github.io#133]
https://music-encoding.org/resources/background.html refers to some literature without giving full refereces. @pe-ro could you have a look, as probably the text goes back to some of your early texts on MEI?

**Comment by bwbohl** [comment]
It's actually one reference, the one to Maxwell 1981

**Comment by ahankinson** [comment]
I wrote this bit -- The reference is:

Maxwell, J.T. 1981. Mockingbird: An interactive composer's aid. M.S. thesis,  Dept. of Electrical Engineering and Computer Science, Massachusetts Institute of Technology.

http://dspace.mit.edu/handle/1721.1/15893

**Comment by martha-thomae** [comment]
Thanks for checking on this, @bwbohl. I felt conflicted about just removing it and was planning on emailing Perry. An issue was a better solution. I will make the changes today.

I guess I should not include this source in the ["Selected Bibliography"](https://music-encoding.org/resources/bibliography.html) because this is not a source talking about MEI. So, instead, I could add a section at the end of ["Background"](https://music-encoding.org/resources/background.html) (where this reference appears) to include all references. Sounds like a good solution? Or just add the link where the reference to Maxwell appears?

Thanks again, @bwbohl! And thanks for providing the full reference, @ahankinson!

**Comment by martha-thomae** [comment]
Solved in PR https://github.com/music-encoding/music-encoding.github.io/pull/134

**Comment by bwbohl** [comment]
thanks to both of you!

@martha-thomae  I think it's a good idea to also include a section with all references at the end of the "Background" page. Nevertheless I like your idea in adding it to some structured bibliography… we should come up with some concept, e.g. a  reading list for background matter
