### ISSUE TITLE
Link to the right PDFs in the 2019 program page.

### ISSUE THREAD

**Issue by vigliensoni** [music-encoding/music-encoding.github.io#170]
Currently, 

All papers linked in the 2019 program page (https://music-encoding.org/conference/2019/program/) throw a 404.

For example: 

- https://music-encoding.org/conference/2019/abstracts_mec2019/VienneseBallet.pdf
- https://music-encoding.org/conference/2019/abstracts_mec2019/MEC%20SIMSSA%20DB.pdf
- https://music-encoding.org/conference/2019/abstracts_mec2019/WEIGL-MEC-TROMPA.pdf

**Comment by musicEnfanthen** [comment]
The subfolder `_conferences/2019/abstracts_mec2019` is completely ignored in the Jekyll build as a subfolder, but all files included in the subfolder are moved to the root level. As it turns out, this is by purpose due to Jekylls blog-oriented structure, and they are not going to change it: https://github.com/jekyll/jekyll/issues/881

Some possible solutions are mentioned in the issue, and also here: https://stackoverflow.com/questions/10363812/local-post-assets-with-jekyll/35270428#35270428

The proposed solutions would require quite some refactoring of the folder structure. 

One quick solution could be to move abstracts to `downloads` folder and get it from there.

@bwbohl what do you think?

**Comment by musicEnfanthen** [comment]
After some investigation, I moved abstracts from build folder `_conferences` to existing static folder `conference` (cf. PR).

**Comment by bwbohl** [comment]
wouldn't it work with the asset plugin mentioned above?

**Comment by musicEnfanthen** [comment]
Maybe, but so it works without plugins ;)
