### ISSUE TITLE
Menu entry for development version of guidelines throws 404

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#195]
When trying to get to the development version of the guidelines it resolves [this link](https://music-encoding.org/guidelines/dev/) which shows a 404 error.

Relates to #189

**Comment by musicEnfanthen** [comment]
Yes, can confirm. 

The links for v3 and v4 are redirected to `guidelines/<version>/content` via `index.html` files in the guidelines repo: https://github.com/music-encoding/guidelines/blob/master/v4/index.html

Such a file is missing for the dev version, so the link does not get resolved properly.

**Comment by bwbohl** [comment]
yes, currently we still have to fix some issues concerning building dev. Thx. for reporting ;-)

**Comment by lpugin** [comment]
FYI, the search functionality is no longer active in the dev version.

**Comment by bwbohl** [comment]
> FYI, the search functionality is no longer active in the dev version.

is that by intention?

**Comment by lpugin** [comment]
Yes. Now that we removed Jekyll we need an XSLT that builds the search index.

**Comment by kepper** [comment]
@lpugin: Could you direct me to something that explains what I need to generate? Thanks!

**Comment by lpugin** [comment]
This output should be JSON object looking like this https://github.com/music-encoding/guidelines/blob/master/js/tipuesearch/search_content_v4.js (Obviously `tags` is not needed)

It is currently in the root of the guidelines. We should load it from the subdirectory of each version. That is, instead of `/js/tipuesearch/search_content_v4.js` it should be `./tipuesearch/search_content.js` within `/dev`, which you can generate with your XSLT.

**Comment by bwbohl** [comment]
fixed with https://github.com/music-encoding/music-encoding/pull/743
