### ISSUE TITLE
Obfuscate mail addresses

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding.github.io#200]
When posting mail addresses on the website, we should find a way to obfuscate them to throw off bots that harvest email addresses for spamming.

Cf. https://alexwlchan.net/2019/06/a-jekyll-filter-for-obfuscating-email-addresses/

**Comment by craigsapp** [comment]
That will work until the harvesters reverse engineer that filter :-)

**Comment by musicEnfanthen** [comment]
Yes, probably. So what would be your advice? Some kind of filter is 1) better than nothing, or 2) totally useless...?

**Comment by craigsapp** [comment]
I just have all of my email sent to Gmail, and they have pretty good junkmail filters.  

But otherwise, I would think an impromptu system for obfuscation would be more robust that a prebuilt one -- especially if the prebuilt one becomes popular.

Some good methods I have tried is to replace ASCII letters with unicode ones that look visually similar, such as this character 🍥 (fish cake with swirl) for an `@` character.  Also a good thing to hide would be to use a non-ascii character that looks like `.` before the top level domain, since that would make it hard to identify without the ending of an email address (as well as a missing `@` sign).  Other possibilities would be to add small spaces around the at symbol or other characters (https://en.wikipedia.org/wiki/Thin_space) that javascript `element.textContent` does not filter out.

**Comment by craigsapp** [comment]
I haven't tried the thin-space idea, but that might be a problem if a real person trying to email legitimately cannot see the space in order to remove it...

**Comment by kepper** [comment]
During ODD Friday, there seemed very little "pressure" to actually implement this. We decided to close for now. If this is creating huge problems for some, please re-open…
