### ISSUE TITLE
Images not properly loaded in Neume Notation Documentation

### ISSUE THREAD

**Issue by carrieeex** [music-encoding/music-encoding.github.io#239]
Most images are not loaded in the [Documentation of Neume Notation](https://music-encoding.org/guidelines/v4/content/neumes.html), like this:
<img width="693" alt="MEI website - Neume Notation" src="https://user-images.githubusercontent.com/59303880/120481348-9b45cc00-c3e2-11eb-802d-eb033c7c7d7a.png">

**Comment by musicEnfanthen** [comment]
Thanks for catching, @carrieeex ! 

This issue should be discussed on music-encoding main repo, since the guidelines are generated from there.

@music-encoding/core-contributors Could you please transfer this issue to [music-encoding/music-encoding](https://github.com/music-encoding/music-encoding)?

**Comment by carrieeex** [comment]
Thank you @musicEnfanthen for the clarification! Sorry I wasn't aware of that. I just opened this [issue](https://github.com/music-encoding/music-encoding/issues/810) to the music-encoding repo.

**Comment by musicEnfanthen** [comment]
Thank you!
