### ISSUE TITLE
Guidelines: Search results link to nowhere

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding.github.io#331]
When searching in the Guidelines for development version, the results are shown in a nice modal, but the links follow the results from the MEI4 version, leading to a 404.

**Comment by bwbohl** [comment]
I can confirm this

**Comment by kepper** [comment]
It seems like the linked paths are lacking the `/dev/` section – I'll look into this tomorrow…

**Comment by kepper** [comment]
I guess I spotted the problem. When built locally, the generated URLs make perfect sense and resolve correctly. The officially deployed version seems to operate from a different folder, so that it is unnecessary / counterproductive to remove path segments (see https://github.com/music-encoding/music-encoding/blob/82c26b329a933c2a2993cc5d214c2917a448fa1f/utils/guidelines_xslt/odd2html/generateSearchIndex.xsl#L28 and several similar lines below). Will prepare a PR…
