### ISSUE TITLE
Merge 'Tools' and 'Repositories'?

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding.github.io#5]
I've been working on some content for these pages, but am a bit confused about the distinction. I was thinking we could provide a list of "Official" repositories, and then a list of 'Community' repositories. Thoughts?

**Comment by lpugin** [comment]
I am not sure we need other community repositories because we already have the tools page and the project page that leads to them. I would here only describe the repositories of music-encoding

**Comment by ahankinson** [comment]
There are cases, though, when a tool is not a project. The MEI Test Set, for example, which is a DDMAL project. Or libmei, which is technically also still a DDMAL project. Or perhaps MerMEId? Or Verovio?

I tend to think of the projects page as 'people using MEI to do something' and tools being 'the things people use to do their projects.'

**Comment by lpugin** [comment]
On Oct 13, 2017 9:25 PM, "Andrew Hankinson" <notifications@github.com>
wrote:

There are cases, though, when a tool is not a project. The MEI Test Set,
for example, which is a DDMAL project. Or libmei, which is technically also
still a DDMAL project. Or perhaps MerMEId? Or Verovio?

I tend to think of the projects page as 'people using MEI to do something'
and tools being 'the things people use to do their projects.'

Yes. Isn't it what we have? For example, Verovio listed in tools, and the
Beethovens Werkstatt listed in projects.


—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/music-encoding/music-encoding.github.io/issues/5#issuecomment-336545539>,
or mute the thread

**Comment by ahankinson** [comment]
There are really only four official repositories needing to be listed: music-encoding, sample-encodings,  encoding-tools, and customeization. Of these, only the first really needs to be described beyond "it is what it says it is, and anything else, see the README for that project."

I propose that we merge them so that people looking for "Tools" only have to look in one place. I don't think we need to make the distinction between "official tools" (repositories) and "other tools" (tools). 

So the proposal is:

#. Make one page called "Tools"
#. Place the official tools under the heading "Official Tools"
#. Place other tools under the heading "Community Tools"

**Comment by lpugin** [comment]
Sounds good to me

**Comment by lpugin** [comment]
2ef2c0746488808272502d2713bf0979256e6f29

**Comment by lpugin** [comment]
2ef2c0746488808272502d2713bf0979256e6f29
